---------------------------------------------------------------
--------------------- SETUPING SCHEMA -------------------------
---------------------------------------------------------------

DROP SCHEMA IF EXISTS `siagetrans`;
CREATE SCHEMA `siagetrans`;


---------------------------------------------------------------
----------------- CREATING A READER USER ----------------------
---------------------------------------------------------------

DROP USER IF EXISTS 'lsiagetrans'@'localhost';
CREATE USER 'lsiagetrans'@'localhost' IDENTIFIED BY '123abc';
GRANT INSERT,SELECT,UPDATE,DELETE ON siagetrans.* TO 'lsiagetrans'@'localhost';

---------------------------------------------------------------
-------------------- CREATING TABLES --------------------------
---------------------------------------------------------------

CREATE TABLE `siagetrans`.`weathermeasurements` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_REGION` VARCHAR(5) NOT NULL,
  `DT_MEASUREMENT` DATETIME NOT NULL,
  `NR_TEMPERATURE_C` DECIMAL NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `WEATHERMEASUREMENTS_ID_UNIQUE` (`ID` ASC) VISIBLE);

CREATE TABLE `siagetrans`.`roads` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  `DS_ZIPCODE` VARCHAR(8) NOT NULL,
  `DS_ADDRESS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ROADS_ID_UNIQUE` (`ID` ASC) VISIBLE);

CREATE TABLE `siagetrans`.`roadsections` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  `ID_ROAD` INT NOT NULL,
  `ES_STATUS` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ROADSECTIONS_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_ROADSECTIONS_ROADS_ID_ROAD_idx` (`ID_ROAD` ASC) VISIBLE,
  CONSTRAINT `FK_ROADSECTIONS_ROADS_ID_ROAD`
    FOREIGN KEY (`ID_ROAD`)
    REFERENCES `siagetrans`.`roads` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE `siagetrans`.`sidewalks` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SIDEWALKS_ID_UNIQUE` (`ID` ASC) VISIBLE);

CREATE TABLE `siagetrans`.`crosswalks` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  `ID_ROADSECTION` INT NOT NULL,
  `ES_STATUS` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `CROSSWALKS_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_CROSSWALKS_ROADSECTIONS_ID_ROADSECTION_idx` (`ID_ROADSECTION` ASC) VISIBLE,
  CONSTRAINT `FK_CROSSWALKS_ROADSECTIONS_ID_ROADSECTION`
    FOREIGN KEY (`ID_ROADSECTION`)
    REFERENCES `siagetrans`.`roadsections` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE `siagetrans`.`sidewalk_crosswalk` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_SIDEWALK` INT NOT NULL,
  `ID_CROSSWALK` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SIDEWALKCROSSWALK_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_SIDEWALKCROSSWALK_SIDEWALKS_ID_SIDEWALK_idx` (`ID_SIDEWALK` ASC) VISIBLE,
  INDEX `FK_SIDEWALKCROSSWALK_CROSSWALKS_ID_CROSSWALK_idx` (`ID_CROSSWALK` ASC) VISIBLE,
  CONSTRAINT `FK_SIDEWALKCROSSWALK_SIDEWALK_ID_SIDEWALK`
    FOREIGN KEY (`ID_SIDEWALK`)
    REFERENCES `siagetrans`.`sidewalks` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_SIDEWALKCROSSWALK_CROSSWALK_ID_CROSSWALK`
    FOREIGN KEY (`ID_CROSSWALK`)
    REFERENCES `siagetrans`.`crosswalks` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE `siagetrans`.`trafficlights` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  `ID_ROADSECTION` INT NOT NULL,
  `NR_GREENTIME_S` INT NOT NULL,
  `NR_YELLOWTIME_S` INT NOT NULL,
  `NR_REDTIME_S` INT NOT NULL,
  `ES_STATUS` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `TRAFFICLIGHTS_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_TRAFFICLIGHTS_ROADSECTIONS_ID_ROADSECTION_idx` (`ID_ROADSECTION` ASC) VISIBLE,
  CONSTRAINT `FK_TRAFFICLIGHTS_ROADSECTIONS_ID_ROADSECTION`
    FOREIGN KEY (`ID_ROADSECTION`)
    REFERENCES `siagetrans`.`roadsections` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE `siagetrans`.`eventtype` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_DESCRIPTION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EVENTTYPE_ID_UNIQUE` (`ID` ASC) VISIBLE);

INSERT INTO `siagetrans`.`eventtype` (DS_DESCRIPTION)
VALUES ('FLOODED ROAD'),('PARTIAL ROAD CLOSURE'),('TOTAL ROAD CLOSURE'),('ROAD ACCIDENT');

CREATE TABLE `siagetrans`.`events` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_EVENTTYPE` INT NOT NULL,
  `DT_CREATION` DATETIME NOT NULL,
  `DT_START` DATETIME NOT NULL,
  `DT_EXPIRATION` DATETIME NULL,
  `DS_COMMENT` VARCHAR(500) NULL,
  `ES_STATUS` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `EVENTS_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_EVENTS_EVENTTYPE_ID_EVENTTYPE_idx` (`ID_EVENTTYPE` ASC) VISIBLE,
  CONSTRAINT `FK_EVENTS_EVENTTYPE_ID_EVENTTYPE`
    FOREIGN KEY (`ID_EVENTTYPE`)
    REFERENCES `siagetrans`.`eventtype` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE `siagetrans`.`roadsection_event` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_ROADSECTION` INT NOT NULL,
  `ID_EVENT` INT NOT NULL,
  `NR_SEVERITY` INT1 UNSIGNED NOT NULL CHECK (NR_SEVERITY BETWEEN 1 AND 10),
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ROADSECTIONEVENT_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_ROADSECTIONEVENT_ROADSECTIONS_ID_ROADSECTION_idx` (`ID_ROADSECTION` ASC) VISIBLE,
  INDEX `FK_ROADSECTIONEVENT_EVENTS_ID_EVENT_idx` (`ID_EVENT` ASC) VISIBLE,
  CONSTRAINT `FK_ROADSECTIONEVENT_ROADSECTION_ID_ROADSECTION`
    FOREIGN KEY (`ID_ROADSECTION`)
    REFERENCES `siagetrans`.`roadsections` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ROADSECTIONEVENT_EVENTS_ID_EVENT`
    FOREIGN KEY (`ID_EVENT`)
    REFERENCES `siagetrans`.`events` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE `siagetrans`.`sidewalkmetrics` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_SIDEWALK` INT NOT NULL,
  `DT_TIMESTAMP` DATETIME NOT NULL,
  `NR_ARRIVERATE` DECIMAL NULL,
  `NR_DEPARTURERATE` DECIMAL NOT NULL,
  `NR_PEDESTRIANCOUNT` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SIDEWALKMETRICS_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_SIDEWALKMETRICS_SIDEWALKS_ID_SIDEWALK_idx` (`ID_SIDEWALK` ASC) VISIBLE,
  CONSTRAINT `FK_SIDEWALKMETRICS_SIDEWALKS_ID_SIDEWALK`
    FOREIGN KEY (`ID_SIDEWALK`)
    REFERENCES `siagetrans`.`sidewalks` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

CREATE TABLE `siagetrans`.`trafficlightmetrics` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_TRAFFICLIGHT` INT NOT NULL,
  `DT_TIMESTAMP` DATETIME NOT NULL,
  `NR_ARRIVERATE` DECIMAL NULL,
  `NR_DEPARTURERATE` DECIMAL NOT NULL,
  `NR_VEHICLECOUNT` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `TRAFFICLIGHTMETRICS_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_TRAFFICLIGHTMETRICS_TRAFFICLIGHT_ID_TRAFFICLIGHT_idx` (`ID_TRAFFICLIGHT` ASC) VISIBLE,
  CONSTRAINT `FK_TRAFFICLIGHTMETRICS_TRAFFICLIGHT_ID_TRAFFICLIGHT`
    FOREIGN KEY (`ID_TRAFFICLIGHT`)
    REFERENCES `siagetrans`.`trafficlights` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

---------------------------------------------------------------
------------------ INSERTING MOCK VALUES ----------------------
---------------------------------------------------------------
  
INSERT INTO `siagetrans`.`weathermeasurements` (DS_REGION, DT_MEASUREMENT, NR_TEMPERATURE_C)
  VALUES ('24210', '2025-03-21 12:00:00.000', 25.0),
         ('24210', '2025-03-22 12:00:00.000', 30.0),
         ('24210', '2025-03-23 12:00:00.000', 28.0);

INSERT INTO `siagetrans`.`roads` (DS_COORDINATES, DS_ZIPCODE, DS_ADDRESS)
VALUES ('-22.9046111,-43.1314167', '24210271', 'Rua Presidente Domiciano');

INSERT INTO `siagetrans`.`roadsections` (DS_COORDINATES, ID_ROAD, ES_STATUS)
VALUES ('-22.9046111,-43.1314167', 1, '1');

INSERT INTO `siagetrans`.`sidewalks` (DS_COORDINATES)
VALUES ('-22.9046111,-43.1314167');

INSERT INTO `siagetrans`.`crosswalks` (DS_COORDINATES, ID_ROADSECTION, ES_STATUS)
VALUES ('-22.9046111,-43.1314167', 1, '1');

INSERT INTO `siagetrans`.`sidewalk_crosswalk` (ID_SIDEWALK, ID_CROSSWALK)
VALUES (1, 1);

INSERT INTO `siagetrans`.`trafficlights` (DS_COORDINATES, ID_ROADSECTION, NR_GREENTIME_S, NR_YELLOWTIME_S, NR_REDTIME_S, ES_STATUS)
VALUES ('-22.9046111,-43.1314167', 1, 30, 5, 20, '1');

INSERT INTO `siagetrans`.`events` (ID_EVENTTYPE, DT_CREATION, DT_START, DT_EXPIRATION, DS_COMMENT, ES_STATUS)
VALUES (1, '2025-03-21 12:00:00.000', '2025-03-21 12:00:00.000', NULL, 'ALAGAMENTO NA RUA DA UFF', '1');

INSERT INTO `siagetrans`.`roadsection_event` (ID_ROADSECTION, ID_EVENT, NR_SEVERITY)
VALUES (1, 1, 5);

INSERT INTO `siagetrans`.`sidewalkmetrics` (ID_SIDEWALK, DT_TIMESTAMP, NR_ARRIVERATE, NR_DEPARTURERATE, NR_PEDESTRIANCOUNT)
VALUES (1, '2025-03-21 12:00:00.000', 10.0, 8.0, 5);

INSERT INTO `siagetrans`.`trafficlightmetrics` (ID_TRAFFICLIGHT, DT_TIMESTAMP, NR_ARRIVERATE, NR_DEPARTURERATE, NR_VEHICLECOUNT)
VALUES (1, '2025-03-21 12:00:00.000', 10.0, 8.0, 5);

