---------------------------------------------------------------
--------------------- SETUPING SCHEMA -------------------------
---------------------------------------------------------------

DROP SCHEMA IF EXISTS `siagetrans`;
CREATE SCHEMA `siagetrans`;


---------------------------------------------------------------
----------------- CREATING A READER USER ----------------------
---------------------------------------------------------------

DROP USER IF EXISTS 'lsiagetrans'@'localhost';
CREATE USER 'lsiagetrans'@'localhost' IDENTIFIED BY '123abc';
GRANT INSERT,SELECT,UPDATE,DELETE ON siagetrans.* TO 'lsiagetrans'@'localhost';

---------------------------------------------------------------
---------------- CREATING CENTRAL TABLES ----------------------
---------------------------------------------------------------

CREATE TABLE `siagetrans`.`roads` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  `DS_ZIPCODE` VARCHAR(8) NOT NULL,
  `DS_ADDRESS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ROADS_ID_UNIQUE` (`ID` ASC) VISIBLE);


CREATE TABLE `siagetrans`.`intersections` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `INTERSECTIONS_ID_UNIQUE` (`ID` ASC) VISIBLE);


CREATE TABLE `siagetrans`.`roadsections` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  `ID_INTERSECTION` INT NOT NULL,
  `ID_ROAD` INT NOT NULL,
  `ES_STATUS` INT1 UNSIGNED NOT NULL CHECK (ES_STATUS BETWEEN 0 AND 1),
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ROADSECTIONS_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_ROADSECTIONS_ROADS_ID_ROAD_idx` (`ID_ROAD` ASC) VISIBLE,
  INDEX `FK_ROADSECTIONS_INTERSECTIONS_ID_INTERSECTION_idx` (`ID_INTERSECTION` ASC) VISIBLE,
  CONSTRAINT `FK_ROADSECTIONS_ROADS_ID_ROAD`
    FOREIGN KEY (`ID_ROAD`)
    REFERENCES `siagetrans`.`roads` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_ROADSECTIONS_INTERSECTIONS_ID_INTERSECTION`
    FOREIGN KEY (`ID_INTERSECTION`)
    REFERENCES `siagetrans`.`intersections` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


CREATE TABLE `siagetrans`.`sidewalks` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  `ID_ROADSECTION` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SIDEWALKS_ID_UNIQUE` (`ID` ASC) VISIBLE),
  INDEX `FK_SIDEWALKS_ROADSECTIONS_ID_ROADSECTION_idx` (`ID_ROADSECTION` ASC) VISIBLE,
  CONSTRAINT `FK_SIDEWALKS_ROADSECTIONS_ID_ROADSECTION`
    FOREIGN KEY (`ID_ROADSECTION`)
    REFERENCES `siagetrans`.`roadsections` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;


---------------------------------------------------------------
----------------- CREATING DOMAIN TABLE -----------------------
---------------------------------------------------------------

CREATE TABLE `siagetrans`.`tsc_types` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_DESCRIPTION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `TSC_TYPE_ID_UNIQUE` (`ID` ASC) VISIBLE);


---------------------------------------------------------------
----------------- CREATING EDGE TABLES ------------------------
---------------------------------------------------------------


CREATE TABLE `siagetrans`.`weather_measurements` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DS_REGION` VARCHAR(5) NOT NULL,
  `DT_MEASUREMENT` DATETIME NOT NULL,
  `NR_TEMPERATURE_C` DECIMAL NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `WEATHER_MEASUREMENTS_ID_UNIQUE` (`ID` ASC) VISIBLE);


CREATE TABLE `siagetrans`.`tsc_programs` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_INTERSECTION` INT NOT NULL,
  `ID_TYPE` INT NOT NULL,
  `NR_YELLOW_DURATION` INT NOT NULL,
  `NR_MINIMUM_DURATION` INT NOT NULL,
  `NR_MAXIMUM_DURATION` INT NOT NULL,
  `NR_EMERGENCY_PRIORIZATION` INT,
  `NR_FLOODING_PRIORIZATION` INT,
  `NR_WEATHER_PRIORIZATION` INT,
  `ES_STATUS` INT1 UNSIGNED NOT NULL CHECK (ES_STATUS BETWEEN 0 AND 1),
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `TSC_PROGRAMS_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_TSC_PROGRAMS_INTERSECTIONS_ID_INTERSECTION_idx` (`ID_INTERSECTION` ASC) VISIBLE,
  INDEX `FK_TSC_PROGRAMS_TSC_TYPE_ID_TYPE_idx` (`ID_TYPE` ASC) VISIBLE,
  CONSTRAINT `FK_TSC_PROGRAMS_INTERSECTIONS_ID_INTERSECTION`
    FOREIGN KEY (`ID_INTERSECTION`)
    REFERENCES `siagetrans`.`intersections` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TSC_PROGRAMS_TSC_TYPE_ID_TYPE`
    FOREIGN KEY (`ID_TYPE`)
    REFERENCES `siagetrans`.`tsc_type` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);


CREATE TABLE `siagetrans`.`tsc_program_phases` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_TSC_PROGRAM` INT NOT NULL,
  `NR_ORDER` INT NOT NULL,
  `NR_GREEN_DURATION` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `TSC_PROGRAM_PHASES_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_TSC_PROGRAM_PHASES_TSC_PROGRAMS_ID_TSC_PROGRAM_idx` (`ID_TSC_PROGRAM` ASC) VISIBLE,
  CONSTRAINT `FK_TSC_PROGRAM_PHASES_TSC_PROGRAMS_ID_TSC_PROGRAM`
    FOREIGN KEY (`ID_TSC_PROGRAM`)
    REFERENCES `siagetrans`.`tsc_programs` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE `siagetrans`.`traffic_lights_per_phase` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_TSC_PROGRAM_PHASE` INT NOT NULL,
  `DS_COORDINATES` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `TRAFFIC_LIGHTS_PER_PHASE_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_TRAFFIC_LIGHTS_PER_PHASE_TSC_PROGRAM_PHASES_ID_TSC_PROGRAM_PHASE_idx` (`ID_TSC_PROGRAM_PHASE` ASC) VISIBLE,
  CONSTRAINT `FK_TRAFFIC_LIGHTS_PER_PHASE_TSC_PROGRAM_PHASES_ID_TSC_PROGRAM_PHASE`
    FOREIGN KEY (`ID_TSC_PROGRAM_PHASE`)
    REFERENCES `siagetrans`.`tsc_program_phases` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE `siagetrans`.`sidewalks_per_phase` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_TSC_PROGRAM_PHASE` INT NOT NULL,
  `ID_SIDEWALK` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `SIDEWALKS_PER_PHASE_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_SIDEWALKS_PER_PHASE_TSC_PROGRAM_PHASES_ID_TSC_PROGRAM_PHASE_idx` (`ID_TSC_PROGRAM_PHASE` ASC) VISIBLE,
  INDEX `FK_SIDEWALKS_PER_PHASE_SIDEWALKS_ID_SIDEWALK_idx` (`ID_SIDEWALK` ASC) VISIBLE,
  CONSTRAINT `FK_SIDEWALKS_PER_PHASE_TSC_PROGRAM_PHASES_ID_TSC_PROGRAM_PHASE`
    FOREIGN KEY (`ID_TSC_PROGRAM_PHASE`)
    REFERENCES `siagetrans`.`tsc_program_phases` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_SIDEWALKS_PER_PHASE_SIDEWALKS_ID_SIDEWALK`
    FOREIGN KEY (`ID_SIDEWALK`)
    REFERENCES `siagetrans`.`sidewalks` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE `siagetrans`.`roadsections_per_phase` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_TSC_PROGRAM_PHASE` INT NOT NULL,
  `ID_ROADSECTION` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ROADSECTIONS_PER_PHASE_ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `FK_ROADSECTIONS_PER_PHASE_TSC_PROGRAM_PHASES_ID_TSC_PROGRAM_PHASE_idx` (`ID_TSC_PROGRAM_PHASE` ASC) VISIBLE,
  INDEX `FK_ROADSECTIONS_PER_PHASE_ROADSECTIONS_ID_ROADSECTION_idx` (`ID_ROADSECTION` ASC) VISIBLE,
  CONSTRAINT `FK_ROADSECTIONS_PER_PHASE_TSC_PROGRAM_PHASES_ID_TSC_PROGRAM_PHASE`
    FOREIGN KEY (`ID_TSC_PROGRAM_PHASE`)
    REFERENCES `siagetrans`.`tsc_program_phases` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_ROADSECTIONS_PER_PHASE_ROADSECTIONS_ID_ROADSECTION`
    FOREIGN KEY (`ID_ROADSECTION`)
    REFERENCES `siagetrans`.`roadsections` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

---------------------------------------------------------------
------------------ INSERTING MOCK VALUES ----------------------
---------------------------------------------------------------
  
INSERT INTO `siagetrans`.`roads` (DS_COORDINATES, DS_ZIPCODE, DS_ADDRESS)
VALUES ('-22.9046111,-43.1314167', '24210271', 'Rua Presidente Domiciano'),
       ('-22.904084, -43.130158', '24210240', 'Rua Passos da Pátria');

INSERT INTO `siagetrans`.`intersections` (DS_COORDINATES)
VALUES ('-22.9046111,-43.1314167');

INSERT INTO `siagetrans`.`roadsections` (DS_COORDINATES, ID_INTERSECTION, ID_ROAD, ES_STATUS)
VALUES ('-22.9046111,-43.1314167', 1, 1, 1),
       ('-22.904084, -43.130158', 1, 2, 1);

INSERT INTO `siagetrans`.`sidewalks` (DS_COORDINATES, ID_ROADSECTION)
VALUES ('-22.9046111,-43.1314167', 1),
       ('-23.9046112,-44.1314168', 1),
       ('-23.9046112,-44.1314168', 2),
       ('-24.9046113,-45.1314169', 2);

INSERT INTO `siagetrans`.`tsc_types` (DS_DESCRIPTION)
VALUES ('FIXED'),('ACTUATED'),('ADAPTATIVE');

INSERT INTO `siagetrans`.`weather_measurements` (DS_REGION, DT_MEASUREMENT, NR_TEMPERATURE_C)
  VALUES ('24210', '2025-03-21 12:00:00.000', 25.0),
         ('24210', '2025-03-22 12:00:00.000', 30.0),
         ('24210', '2025-03-23 12:00:00.000', 28.0);

INSERT INTO `siagetrans`.`tsc_programs` (ID_INTERSECTION, ID_TYPE, NR_YELLOW_DURATION, ES_STATUS)
VALUES (1, 2, 5, 1);

INSERT INTO `siagetrans`.`tsc_program_phases` (ID_TSC_PROGRAM, NR_ORDER, NR_GREEN_DURATION)
VALUES (1, 1, 35),
       (1, 2, 25);

INSERT INTO `siagetrans`.`traffic_lights_per_phase` (ID_TSC_PROGRAM_PHASE, DS_COORDINATES)
VALUES (1, '-22.9046111,-43.1314167'),
       (2, '-22.904084, -43.130158');

INSERT INTO `siagetrans`.`sidewalks_per_phase` (ID_TSC_PROGRAM_PHASE, ID_SIDEWALK)
VALUES (1, 1),
       (2, 1),
       (2, 2);

INSERT INTO `siagetrans`.`roadsections_per_phase` (ID_TSC_PROGRAM_PHASE, ID_SIDEWALK)
VALUES (1, 1),
       (2, 2);